using NUnit.Framework;

namespace TestProject1
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void SkaiciuotiMokescius350Pajamu()
        {
            decimal pajamos = 350m
            decimal expectedPajamos = 17.5m

                var result = AutoGeneratedProgram.SaiciuotiMokescius(pajamos);

            Assert.AreEqual(expectedResult, actualresult);
        }
    }
}